name: aoc2021
version: 0.1.0.0
github: "pwm/aoc2021"
author: "pwm"

extra-source-files:
  - README.md

data-files:
  - input/*.txt

# a set of basic libraries used by most apps
dependencies:
  - base >= 4.7 && < 5
  - advent-of-code-ocr
  - bytestring
  - containers
  - cookie
  - directory
  - filepath
  - generic-lens
  - http-client
  - http-types
  - lens
  - logict
  - megaparsec
  - mtl
  - optparse-applicative
  - parser-combinators
  - pqueue
  - pretty-simple
  - random
  - req
  - split
  - text
  - time
  - transformers
  - unordered-containers
  - vector

library:
  source-dirs: src

executables:
  fetch:
    source-dirs: bin
    main: Fetch.hs
    other-modules: []
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aoc2021
  solve:
    source-dirs: bin
    main: Solve.hs
    other-modules: []
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aoc2021

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - aoc2021
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover == 2.*

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - LambdaCase
  - OverloadedLabels
  - OverloadedStrings
  - PatternSynonyms
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TupleSections
  - TypeApplications
  - TypeOperators

ghc-options:
  - -Weverything
  - -Wno-missing-exported-signatures # missing-exported-signatures turns off the more strict -Wmissing-signatures.
  - -Wno-missing-import-lists # Requires explicit imports of _every_ function (e.g. ‘$’); too strict
  - -Wno-missed-specialisations # When GHC can’t specialize a polymorphic function.
  - -Wno-all-missed-specialisations # See missed-specialisations
  - -Wno-unsafe # Don’t use Safe Haskell warnings
  - -Wno-safe # Don’t use Safe Haskell warnings
  - -Wno-missing-local-signatures # Warning for polymorphic local bindings; nothing wrong with those.
  - -Wno-monomorphism-restriction # Don’t warn if the monomorphism restriction is used
  - -Wno-missing-export-lists # Don't warn if export list is missing
  - -Wno-missing-home-modules # Don't warn in GHCi when loading modules (this is a bogus warning)
  - -Wno-missing-safe-haskell-mode
  - -Wno-prepositive-qualified-module
  - -Wno-unused-packages
  - -Wno-implicit-prelude
